FROM amazon/aws-lambda-python:3.11

RUN mkdir -p /root/.ollama/models
COPY models /root/.ollama/models/
COPY lambda_function.py .

RUN pip install ollama

ENV OLLAMA_HOST=0.0.0.0

CMD [ "lambda_function.lambda_handler" ]
